---
# Set the default language for ToolsPro
# Available languages: russian, english, chinese
# English message resource by @Pub4Game, @fromgate and @mik2212 (GitHub)
# Chinese message resource by @xuxugzs (GitHub)
general:
  language: english
  debug-mode: false
forbidden-player-names:
  - Steve
  - Notch
JoinSurvival: false
TellNotice: false